DEBUG: true
ALLOWED_HOSTS:
  - '*'
DATABASES.default.NAME: postgres
DATABASES.default.USER: postgres
DATABASES.default.PASSWORD: postgres
DATABASES.default.HOST: localhost
DATABASES.default.PORT: 5432