# Generated by Django 5.2.9 on 2025-12-26 00:40

import datetime
import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('created', models.DateTimeField(default=datetime.datetime(2025, 12, 26, 3, 40, 55, 232887))),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=127)),
                ('content', models.CharField(max_length=4095)),
                ('media_type', models.CharField(blank=True, max_length=15, null=True)),
                ('media_url', models.CharField(blank=True, max_length=2047, null=True)),
                ('user_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event_Tag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.tag')),
            ],
        ),
    ]
