# Generated by Django 5.2.9 on 2026-01-18 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='media_bytes',
            field=models.BinaryField(blank=True, max_length=65536, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 18, 22, 26, 58, 16856)),
        ),
    ]
