# Generated by Django 5.2.9 on 2026-01-19 20:17

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_media_bytes_alter_event_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
        ),
    ]
